<?php
# This file was automatically generated by the MediaWiki 1.26.3
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Star Citizen";
$wgMetaNamespace = "Star_Citizen";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";
$wgScriptExtension = "$wgScriptPath/index.php";
$wgRedirectScript   = "$wgScriptPath/redirect.php";
$wgArticlePath = "/$1";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://starcitizen.tools";


## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "$wgResourceBasePath/resources/assets/sclogo.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "apache@starcitizen.tools";
$wgPasswordSender = "apache@starcitizen.tools";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "REDACTED";
$wgDBserver = "REDACTED";
$wgDBname = "REDACTED";
$wgDBuser = "REDACTED";
$wgDBpassword = "REDACTED";

# MySQL specific settings
$wgDBprefix = "wiki";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=utf8";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgGenerateThumbnailOnParse = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "en";

$wgSecretKey = "REDACTED";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "REDACTED";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://creativecommons.org/licenses/by-sa/3.0/";
$wgRightsText = "Creative Commons Attribution-ShareAlike";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/cc-by-sa.png";
$wgFavicon = "$wgScriptPath/favicon.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = true;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['sysop']['edit'] = true;
$wgAllowUserCss = true;


## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'Vector' );

#Maintenance
#$wgReadOnly = 'Maintenance is underway. Website is on read-only mode';

#SVG Support
$wgFileExtensions[] = 'svg';
$wgAllowTitlesInSVG = true;
$wgSVGConverter = 'ImageMagick';

#Enabled Extensions.
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'EmbedVideo' );
wfLoadExtension( 'MsUpload' );
$wgMSU_useDragDrop = true;
$wgMSU_showAutoCat = true;
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'WikiSEO' );
wfLoadExtension( 'Cite' );
wfLoadExtension("DynamicPageList");
wfLoadExtension( 'Nuke' );
wfLoadExtension( 'CommonsMetadata' );
wfLoadExtension( 'ReplaceText' );
require_once "$IP/extensions/MultimediaViewer/MultimediaViewer.php";
$wgMediaViewerEnableByDefault = true;
$wgMediaViewerEnableByDefaultForAnonymous = true;
require_once "$IP/extensions/Echo/Echo.php";
wfLoadExtension( 'RevisionSlider' );
wfLoadExtension( 'CheckUser' );
require_once "$IP/extensions/Tabber/Tabber.php";
require_once "$IP/extensions/RSS/RSS.php";
require_once "$IP/extensions/PageImages/PageImages.php";
wfLoadExtension( 'TextExtracts' );
wfLoadExtension( 'Popups' );
$wgExtractsRemoveClasses[] = 'dablink';
$wgExtractsRemoveClasses[] = 'translate';

#CSS
require_once "$IP/extensions/CSS/CSS.php";

#Antispam
#require_once "$IP/extensions/Antispam/Antispam.php";
wfLoadExtensions( array( 'ConfirmEdit', 'ConfirmEdit/ReCaptchaNoCaptcha' ) );
$wgCaptchaClass = 'ReCaptchaNoCaptcha';
$wgReCaptchaSiteKey = 'REDACTED';
$wgReCaptchaSecretKey = 'REDACTED';

#Flow
require_once "$IP/extensions/Flow/Flow.php";

#Javascript
$wgHooks['BeforePageDisplay'][] ='onBeforePageDisplay';

function onBeforePageDisplay( OutputPage &$out, Skin &$skin )
{
    $script = '<script></script>';
    $out->addHeadItem("head script", $script);
    return true;
};


#Translate Plugin
wfLoadExtension( 'Babel' );
wfLoadExtension( 'cldr' );
wfLoadExtension( 'CleanChanges' );
$wgCCTrailerFilter = true;
$wgCCUserFilter = false;
$wgDefaultUserOptions['usenewrc'] = 1;
wfLoadExtension( 'LocalisationUpdate' );
$wgLocalisationUpdateDirectory = "$IP/cache";
require_once "$IP/extensions/Translate/Translate.php";
$wgGroupPermissions['sysop']['pagetranslation'] = true;
$wgGroupPermissions['sysop']['translate-manage'] = true;
$wgTranslateDocumentationLanguageCode = 'qqq';
$wgExtraLanguageNames['qqq'] = 'Message documentation'; # No linguistic content. Used for documenting messages
wfLoadExtension( 'UniversalLanguageSelector' );

#Google Analytics
require_once "$IP/extensions/googleAnalytics/googleAnalytics.php";
$wgGoogleAnalyticsAccount = 'UA-48789297-5';



#Visual Editor
require_once "$IP/extensions/VisualEditor/VisualEditor.php";

// Enable by default for everybody
$wgDefaultUserOptions['visualeditor-enable'] = 1;

// Don't allow users to disable it
$wgHiddenPrefs[] = 'visualeditor-enable';


$wgVirtualRestConfig['modules']['parsoid'] = array(
  // URL to the Parsoid instance
  // Use port 8142 if you use the Debian package
  'url' => 'http://starcitizen.tools:8142',

);

# Add more configuration options below.
define("NS_COMMLINK", 3000);
define("NS_COMMLINK_TALK", 3001);
$wgExtraNamespaces[NS_COMMLINK] = "Comm-Link";
$wgExtraNamespaces[NS_COMMLINK_TALK] = "Comm-Link_talk";
$wgNamespacesWithSubpages[3001] = true;
$wgNamespacesToBeSearchedDefault[NS_COMMLINK] = true;
$wgVisualEditorAvailableNamespaces = array(
NS_MAIN     => true,
NS_USER     => true,
NS_HELP     => true,
NS_PROJECT  => true,
NS_COMMLINK => true
);

$wgNamespaceContentModels[NS_TALK] = CONTENT_MODEL_FLOW_BOARD;
$wgNamespaceContentModels[NS_USER_TALK] = CONTENT_MODEL_FLOW_BOARD;
$wgNamespaceContentModels[NS_COMMLINK_TALK] = CONTENT_MODEL_FLOW_BOARD;
$wgNamespaceContentModels[NS_PROJECT_TALK] = CONTENT_MODEL_FLOW_BOARD;
$wgNamespaceContentModels[NS_FILE_TALK] = CONTENT_MODEL_FLOW_BOARD;
$wgNamespaceContentModels[NS_MEDIAWIKI_TALK] = CONTENT_MODEL_FLOW_BOARD;
$wgNamespaceContentModels[NS_TEMPLATE_TALK] = CONTENT_MODEL_FLOW_BOARD;
$wgNamespaceContentModels[NS_HELP_TALK] = CONTENT_MODEL_FLOW_BOARD;
$wgNamespaceContentModels[NS_CATEGORY_TALK] = CONTENT_MODEL_FLOW_BOARD;
$wgNamespaceContentModels[NS_TRANSLATIONS_TALK] = CONTENT_MODEL_FLOW_BOARD;
$wgNamespaceProtection[NS_TEMPLATE] = array( 'template-edit' );
$wgFlowEditorList = array( 'visualeditor', 'none' );
$wgFlowContentFormat = 'html';

#Scribunto
require_once "$IP/extensions/Scribunto/Scribunto.php";
$wgScribuntoDefaultEngine = 'luastandalone';

#Permissions

#User
$wgGroupPermissions['user']['edit'] = false;
$wgGroupPermissions['user']['minoredit'] = false;
$wgGroupPermissions['user']['move'] = false;
$wgGroupPermissions['user']['movefile'] = false;
$wgGroupPermissions['user']['move-categorypages'] = false;
$wgGroupPermissions['user']['move-rootuserpages'] = false;
$wgGroupPermissions['user']['move-subpages'] = false;
$wgGroupPermissions['user']['reupload'] = false;
$wgGroupPermissions['user']['translate'] = false;
$wgGroupPermissions['user']['translate-import'] = false;
$wgGroupPermissions['user']['translate-groupreview'] = false;
$wgGroupPermissions['user']['flow-lock'] = false;

#Verified
$wgGroupPermissions['Verified'] = $wgGroupPermissions['user'];
$wgGroupPermissions['Verified']['edit'] = true;
$wgGroupPermissions['Verified']['skipcaptcha'] = true;


#Translator
$wgGroupPermissions['Translator'] = $wgGroupPermissions['Verified'];
$wgGroupPermissions['Translator']['translate'] = true;
$wgGroupPermissions['Translator']['translate-import'] = true;
$wgGroupPermissions['Translator']['translate-messagereview'] = true;


#Trusted
$wgGroupPermissions['Trusted'] = $wgGroupPermissions['Verified'];
$wgGroupPermissions['Trusted']['minoredit'] = true;
$wgGroupPermissions['Trusted']['autoconfirmed'] = true;
$wgGroupPermissions['Trusted']['move'] = true;
$wgGroupPermissions['Trusted']['move-subpages'] = true;
$wgGroupPermissions['Trusted']['reupload'] = true;

#Editor
$wgGroupPermissions['Editor'] = $wgGroupPermissions['Trusted'];
$wgGroupPermissions['Editor']['noratelimit'] = true;
$wgGroupPermissions['Editor']['patrol'] = true;
$wgGroupPermissions['Editor']['delete'] = true;
$wgGroupPermissions['Editor']['movefile'] = true;
$wgGroupPermissions['Editor']['move-categorypages'] = true;
$wgGroupPermissions['Editor']['template-edit'] = true;
$wgGroupPermissions['Editor']['pagetranslation'] = true;
$wgAddGroups['Editor'] = array( 'Verified' );

#Chief Editor
$wgGroupPermissions['ChiefEditor'] = $wgGroupPermissions['Editor'];
$wgGroupPermissions['ChiefEditor']['autopatrol'] = true;
$wgGroupPermissions['ChiefEditor']['editinterface'] = true;
$wgGroupPermissions['ChiefEditor']['block'] = true;
$wgGroupPermissions['ChiefEditor']['protect'] = true;
$wgGroupPermissions['ChiefEditor']['editprotected'] = true;
$wgGroupPermissions['ChiefEditor']['suppressredirect'] = true;
$wgGroupPermissions['ChiefEditor']['undelete'] = true;
$wgGroupPermissions['ChiefEditor']['mergehistory'] = true;
$wgGroupPermissions['ChiefEditor']['bigdelete'] = true;
$wgGroupPermissions['ChiefEditor']['browserarchive'] = true;
$wgGroupPermissions['ChiefEditor']['rollback'] = true;
$wgGroupPermissions['ChiefEditor']['deletedhistory'] = true;
$wgGroupPermissions['ChiefEditor']['deletedtext'] = true;
$wgAddGroups['ChiefEditor'] = array( 'Verified', 'Trusted', 'Translator' );
$wgGroupPermissions['ChiefEditor']['checkuser'] = true;
$wgGroupPermissions['ChiefEditor']['checkuser-log'] = true;
$wgGroupPermissions['ChiefEditor']['flow-create-board'] = true;
$wgGroupPermissions['ChiefEditor']['translate-proofr'] = true;
$wgGroupPermissions['ChiefEditor']['translate-manage'] = true;
$wgGroupPermissions['ChiefEditor']['translate'] = true;
$wgGroupPermissions['ChiefEditor']['translate-groupreview'] = true;
$wgGroupPermissions['ChiefEditor']['replacetext'] = true;


#Administrator
$wgGroupPermissions['Admin'] = $wgGroupPermissions['ChiefEditor'];
$wgGroupPermissions['Admin']['userrights'] = true;
