<?php

$languageNames = [
	'nds-nl' => 'West Low German',
];

$currencyNames = [
	'ILR' => 'Israeli Shekel (1980–1985)',
	'ILS' => 'Israeli New Shekel',
];

$timeUnits = [
	'hour-narrow-future-one' => 'in {0} hr',
	'hour-narrow-future-other' => 'in {0} hr',
	'hour-narrow-past-one' => '{0} hr ago',
	'hour-narrow-past-other' => '{0} hr ago',
	'hour-short-future-one' => 'in {0} hr',
	'hour-short-future-other' => 'in {0} hr',
	'hour-short-past-one' => '{0} hr ago',
	'hour-short-past-other' => '{0} hr ago',
	'minute-narrow-future-one' => 'in {0} min',
	'minute-narrow-future-other' => 'in {0} min',
	'minute-narrow-past-one' => '{0} min ago',
	'minute-narrow-past-other' => '{0} min ago',
	'minute-short-future-one' => 'in {0} min',
	'minute-short-future-other' => 'in {0} min',
	'minute-short-past-one' => '{0} min ago',
	'minute-short-past-other' => '{0} min ago',
	'month-narrow-future-one' => 'in {0} mo',
	'month-narrow-future-other' => 'in {0} mo',
	'month-narrow-past-one' => '{0} mo ago',
	'month-narrow-past-other' => '{0} mo ago',
	'month-short-future-one' => 'in {0} mo',
	'month-short-future-other' => 'in {0} mo',
	'month-short-past-one' => '{0} mo ago',
	'month-short-past-other' => '{0} mo ago',
	'quarter-narrow-future-one' => 'in {0} qtr',
	'quarter-narrow-future-other' => 'in {0} qtr',
	'quarter-narrow-past-one' => '{0} qtr ago',
	'quarter-narrow-past-other' => '{0} qtr ago',
	'quarter-short-future-one' => 'in {0} qtr',
	'quarter-short-future-other' => 'in {0} qtr',
	'quarter-short-past-one' => '{0} qtr ago',
	'quarter-short-past-other' => '{0} qtr ago',
	'second-narrow-future-one' => 'in {0} sec',
	'second-narrow-future-other' => 'in {0} sec',
	'second-narrow-past-one' => '{0} sec ago',
	'second-narrow-past-other' => '{0} sec ago',
	'second-short-future-one' => 'in {0} sec',
	'second-short-future-other' => 'in {0} sec',
	'second-short-past-one' => '{0} sec ago',
	'second-short-past-other' => '{0} sec ago',
	'week-narrow-future-one' => 'in {0} wk',
	'week-narrow-future-other' => 'in {0} wk',
	'week-narrow-past-one' => '{0} wk ago',
	'week-narrow-past-other' => '{0} wk ago',
	'week-short-future-one' => 'in {0} wk',
	'week-short-future-other' => 'in {0} wk',
	'week-short-past-one' => '{0} wk ago',
	'week-short-past-other' => '{0} wk ago',
	'year-narrow-future-one' => 'in {0} yr',
	'year-narrow-future-other' => 'in {0} yr',
	'year-narrow-past-one' => '{0} yr ago',
	'year-narrow-past-other' => '{0} yr ago',
	'year-short-future-one' => 'in {0} yr',
	'year-short-future-other' => 'in {0} yr',
	'year-short-past-one' => '{0} yr ago',
	'year-short-past-other' => '{0} yr ago',
];
