<?php

$languageNames = [
	'ar' => 'Arabek',
	'ar-001' => 'Arabek Savonek Arnowydh',
	'br' => 'Bretonek',
	'cy' => 'Kembrek',
	'da' => 'Danek',
	'de' => 'Almaynek',
	'de-at' => 'Almaynek (Ostri)',
	'de-ch' => 'Almaynek Ughel (Pow Swis)',
	'el' => 'Greka',
	'en' => 'Sowsnek',
	'en-au' => 'Sowsnek (Ostrali)',
	'en-ca' => 'Sowsnek (Kanada)',
	'en-gb' => 'Sowsnek (Breten Veur)',
	'es' => 'Spaynek',
	'eu' => 'Baskek',
	'fr' => 'Frenkek',
	'fr-ca' => 'Frenkek (Kanada)',
	'fr-ch' => 'Frenkek (Pow Swis)',
	'ga' => 'Wordhonek',
	'gd' => 'Godhalek Alban',
	'it' => 'Italek',
	'ja' => 'Japanek',
	'kw' => 'kernewek',
	'nl' => 'Iseldiryek',
	'pt' => 'Portyngalek',
	'pt-pt' => 'Portyngalek (Ewrop)',
	'ro-md' => 'Moldavek',
	'ru' => 'Russek',
	'yue' => 'Kantonek',
	'zh' => 'Chinek',
	'zh-hans' => 'Chinek sempelhes',
	'zh-hant' => 'Chinek hengovek',
];

$currencyNames = [
	'EUR' => 'Euro',
];

$countryNames = [
	'BR' => 'Brasil',
	'CN' => 'China',
	'DE' => 'Almayn',
	'EU' => 'Unyans Europek',
	'FR' => 'Pow Frenk',
	'GB' => 'Rywvaneth Unys',
	'IN' => 'Eynda',
	'IT' => 'Itali',
	'JP' => 'Japan',
	'RU' => 'Russi',
	'UN' => 'Kenedhlow Unys',
	'US' => 'Statys Unys',
];
