# -*- coding: utf-8 -*-
from eventlogging.factory import reads


@reads('mock')
def mock_writer():
    """A mock EventLogging writer used for testing the plug-in auto-loader."""
    while 1:
        yield 'value generated by plug-in'
